
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 77
#define YY_END_OF_BUFFER 78
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[307] =
    {   0,
       60,   60,    0,    0,   78,   76,   74,   75,   62,   64,
       62,   76,   61,   62,   62,   57,   69,   70,   68,   76,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   76,   66,   66,   71,   64,    0,   59,    0,   65,
       57,   57,   73,   54,   72,    0,   56,   58,   58,   58,
        2,   58,   18,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   40,   58,   58,   58,   58,
       58,   37,   39,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,    0,   67,   63,   57,

       55,   56,    4,   38,   44,   58,   58,   58,   58,   58,
       58,   58,   58,   49,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   41,   58,   58,
       58,   58,   58,   26,   58,   58,   58,   58,   58,   58,
       58,   58,   58,    0,   53,   63,   55,   58,   46,   58,
       58,   58,   45,   58,   50,   58,   14,   58,   58,   58,
       58,   58,   23,   29,   33,   51,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   47,   58,   58,   58,   58,
       48,   58,   58,    1,   58,   31,   58,   58,   58,   17,
       58,   58,   30,   58,   22,   58,   21,   35,   58,   34,

       58,   58,   58,   58,   58,   58,   43,   58,   32,   58,
       16,   58,   27,   58,   58,   42,   19,   58,   24,   58,
       58,    3,   58,   58,   58,   58,   58,   58,   25,   52,
       20,   58,   58,   58,   36,   58,   58,   58,   58,   58,
       58,   58,   28,    5,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   15,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,    6,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   13,   58,   58,   58,   11,   58,
        7,    9,   58,   58,   58,   58,   58,   58,   58,   58,

        8,   10,   58,   58,   12,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    8,    9,    8,
        8,   10,    8,    8,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,    8,   15,
       16,   17,    1,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
        1,    1,    1,    8,   45,   46,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,   67,   68,   69,   70,
       71,   44,    1,    8,    1,    8,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[72] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    1,    1,    5,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    4,    7,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6
    } ;

static yyconst flex_int16_t yy_base[318] =
    {   0,
        0,    0,  580,  576,  583,  599,  599,  599,  564,    0,
      599,  563,  599,  553,  541,   60,   59,  599,  532,  529,
       47,   50,   59,   62,   50,   47,   50,   69,   55,   57,
        0,   71,  100,   93,   80,   73,  107,   77,  102,  116,
      111,    0,  599,  533,  599,    0,  534,  599,  540,  599,
      527,   90,  523,  599,  599,    0,    0,    0,  110,  119,
      122,  119,    0,  109,  126,  110,  113,  114,  115,  132,
      128,  123,  142,  141,  160,  154,  161,  165,  164,  152,
      156,    0,  174,  159,  162,  174,  170,  171,  166,  181,
      178,  184,  180,  180,  188,  180,  492,  599,    0,  523,

        0,    0,    0,    0,    0,  188,  208,  218,  204,  223,
      223,  207,  223,    0,  210,  217,  210,  223,  225,  229,
      230,  221,  223,  218,  234,  231,  221,    0,  238,  239,
      225,  238,  243,    0,  491,  248,  236,  238,  268,  261,
      258,  266,  278,  489,  599,    0,    0,  269,    0,  265,
      267,  285,    0,  279,    0,  269,    0,  274,  277,  489,
      274,  275,    0,    0,    0,    0,  274,  277,  278,  280,
      290,  280,  298,  328,  295,    0,  291,  286,  302,  320,
        0,  330,  321,    0,  333,    0,  338,  326,  322,    0,
      336,  328,    0,  325,    0,  345,    0,    0,  328,    0,

      329,  341,  350,  337,  341,  348,    0,  351,    0,  338,
        0,  337,    0,  342,  362,    0,    0,  363,    0,  374,
      378,    0,  384,  386,  382,  488,  394,  388,    0,    0,
        0,  392,  378,  390,    0,  385,  487,  395,  399,  400,
      392,  385,    0,  388,  392,  394,  392,  406,  486,  404,
      401,  485,  401,  399,    0,  413,  403,  431,  441,  484,
      433,  424,  439,  431,  483,  436,  449,  435,  439,    0,
      435,  435,  439,  437,  451,  455,  452,  437,  451,  459,
      452,  462,  449,  455,    0,  452,  454,  470,    0,  456,
        0,    0,  472,  275,  486,  487,  485,  484,  486,  492,

        0,    0,  485,  490,    0,  599,  555,  562,  569,  572,
      575,   91,   85,  578,  581,  588,  592
    } ;

static yyconst flex_int16_t yy_def[318] =
    {   0,
      306,    1,  307,  307,  306,  306,  306,  306,  306,  308,
      306,  309,  306,  306,  306,  306,  306,  306,  306,  310,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  312,  306,  306,  306,  308,  309,  306,  306,  306,
      306,  306,  306,  306,  306,  313,  314,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  315,  306,  316,  306,

      317,  314,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  315,  306,  316,  317,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,

      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,

      311,  311,  311,  311,  311,    0,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306
    } ;

static yyconst flex_int16_t yy_nxt[671] =
    {   0,
        6,    7,    8,    7,    9,    6,   10,   11,   12,   13,
       14,   11,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       31,   33,   34,   35,   31,   36,   37,   38,   39,   40,
       41,   31,   31,   31,    6,   42,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   31,   33,
       34,   35,   31,   36,   37,   38,   39,   40,   41,   31,
       31,   51,   62,   52,   53,   54,   59,   64,   60,   69,
       66,   70,   72,   61,   67,   73,   76,   74,   68,   77,
      101,   71,   63,   78,   65,   75,   97,   79,   85,   86,

       62,   51,   90,   52,   59,   64,   60,   69,   66,   70,
       72,   61,   67,   73,   76,   74,   68,   77,   80,   71,
       63,   78,   65,   75,   82,   79,   85,   86,   83,   87,
       90,   84,   81,   91,   94,   92,   95,   96,   93,  103,
      104,   88,  105,  106,   89,  107,   80,  110,  108,  111,
      112,  113,   82,  114,  115,  116,   83,   87,  109,   84,
       81,   91,   94,   92,   95,   96,   93,  103,  104,   88,
      105,  106,   89,  107,  117,  110,  108,  111,  112,  113,
      118,  114,  115,  116,  119,  120,  109,  123,  124,  127,
      121,  122,  125,  128,  126,  129,  130,  131,  132,  133,

      135,  136,  117,  137,  138,  139,  140,  134,  118,  141,
      142,  143,  119,  120,  148,  123,  124,  127,  121,  122,
      125,  128,  126,  129,  130,  131,  132,  133,  135,  136,
      149,  137,  138,  139,  140,  134,  150,  141,  142,  143,
      151,  152,  148,  153,  154,  155,  156,  157,  158,  159,
      160,  161,  162,  163,  164,  165,  166,  167,  149,  168,
      169,  170,  171,  172,  150,  173,  175,  176,  151,  152,
      177,  153,  154,  155,  156,  157,  158,  159,  160,  161,
      162,  163,  164,  165,  166,  167,  178,  168,  169,  170,
      171,  172,  179,  173,  175,  176,  180,  181,  177,  183,

      184,  182,  185,  186,  187,  188,  189,  190,  191,  193,
      194,  195,  196,  197,  178,  198,  199,  200,  201,  297,
      179,  206,  207,  208,  180,  181,  209,  183,  184,  182,
      185,  186,  187,  188,  189,  190,  191,  193,  194,  195,
      196,  197,  210,  198,  199,  200,  201,  202,  203,  206,
      207,  208,  211,  212,  209,  213,  214,  215,  216,  204,
      217,  218,  219,  220,  205,  221,  222,  223,  225,  226,
      210,  227,  228,  229,  230,  202,  203,  231,  232,  224,
      211,  212,  233,  213,  214,  215,  216,  204,  217,  218,
      219,  220,  205,  221,  222,  223,  225,  226,  234,  227,

      228,  229,  230,  235,  236,  231,  232,  224,  237,  238,
      233,  239,  241,  242,  243,  244,  245,  246,  248,  249,
      250,  251,  252,  253,  254,  255,  234,  256,  257,  259,
      260,  235,  236,  262,  263,  264,  237,  238,  265,  239,
      241,  242,  243,  244,  245,  246,  248,  249,  250,  251,
      252,  253,  254,  255,  266,  256,  257,  259,  260,  267,
      269,  262,  263,  264,  270,  271,  265,  272,  274,  275,
      276,  277,  278,  279,  280,  281,  282,  283,  284,  285,
      286,  287,  266,  288,  289,  290,  291,  267,  269,  292,
      293,  294,  270,  271,  295,  272,  274,  275,  276,  277,

      278,  279,  280,  281,  282,  283,  284,  285,  286,  287,
      296,  288,  289,  290,  291,  298,  299,  292,  293,  294,
      300,  301,  295,  302,  303,  304,  305,  273,  268,  261,
      258,  247,  240,  192,  145,  174,  100,  145,  296,   54,
      100,   99,   48,  298,  299,   98,   56,   55,  300,  301,
       50,  302,  303,  304,  305,   43,   43,   43,   43,   43,
       43,   43,   46,   49,   46,   46,   46,   46,   46,   47,
       47,   48,   47,   47,   47,   47,   57,   57,   58,   45,
       58,  102,  306,  102,  144,   44,  144,  144,  146,   44,
      146,  146,  146,  146,  146,  147,  306,  147,    5,  306,

      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306
    } ;

static yyconst flex_int16_t yy_chk[671] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   16,   22,   16,   17,   17,   21,   23,   21,   25,
       24,   25,   26,   21,   24,   27,   29,   28,   24,   30,
      313,   25,   22,   32,   23,   28,  312,   32,   35,   36,

       22,   52,   38,   52,   21,   23,   21,   25,   24,   25,
       26,   21,   24,   27,   29,   28,   24,   30,   33,   25,
       22,   32,   23,   28,   34,   32,   35,   36,   34,   37,
       38,   34,   33,   39,   40,   39,   41,   41,   39,   59,
       60,   37,   61,   62,   37,   64,   33,   66,   65,   67,
       68,   69,   34,   70,   71,   72,   34,   37,   65,   34,
       33,   39,   40,   39,   41,   41,   39,   59,   60,   37,
       61,   62,   37,   64,   73,   66,   65,   67,   68,   69,
       74,   70,   71,   72,   75,   76,   65,   77,   78,   80,
       76,   76,   79,   81,   79,   83,   84,   85,   86,   87,

       88,   89,   73,   90,   91,   92,   93,   87,   74,   94,
       95,   96,   75,   76,  106,   77,   78,   80,   76,   76,
       79,   81,   79,   83,   84,   85,   86,   87,   88,   89,
      107,   90,   91,   92,   93,   87,  108,   94,   95,   96,
      109,  110,  106,  111,  112,  113,  115,  116,  117,  118,
      119,  120,  121,  122,  123,  124,  125,  126,  107,  127,
      129,  130,  131,  132,  108,  133,  136,  137,  109,  110,
      138,  111,  112,  113,  115,  116,  117,  118,  119,  120,
      121,  122,  123,  124,  125,  126,  139,  127,  129,  130,
      131,  132,  140,  133,  136,  137,  141,  142,  138,  143,

      148,  142,  150,  151,  152,  154,  156,  158,  159,  161,
      162,  167,  168,  169,  139,  170,  171,  172,  173,  294,
      140,  175,  177,  178,  141,  142,  179,  143,  148,  142,
      150,  151,  152,  154,  156,  158,  159,  161,  162,  167,
      168,  169,  180,  170,  171,  172,  173,  174,  174,  175,
      177,  178,  182,  183,  179,  185,  187,  188,  189,  174,
      191,  192,  194,  196,  174,  199,  201,  202,  203,  204,
      180,  205,  206,  208,  210,  174,  174,  212,  214,  202,
      182,  183,  215,  185,  187,  188,  189,  174,  191,  192,
      194,  196,  174,  199,  201,  202,  203,  204,  218,  205,

      206,  208,  210,  220,  221,  212,  214,  202,  223,  224,
      215,  225,  227,  228,  232,  233,  234,  236,  238,  239,
      240,  241,  242,  244,  245,  246,  218,  247,  248,  250,
      251,  220,  221,  253,  254,  256,  223,  224,  257,  225,
      227,  228,  232,  233,  234,  236,  238,  239,  240,  241,
      242,  244,  245,  246,  258,  247,  248,  250,  251,  259,
      261,  253,  254,  256,  262,  263,  257,  264,  266,  267,
      268,  269,  271,  272,  273,  274,  275,  276,  277,  278,
      279,  280,  258,  281,  282,  283,  284,  259,  261,  286,
      287,  288,  262,  263,  290,  264,  266,  267,  268,  269,

      271,  272,  273,  274,  275,  276,  277,  278,  279,  280,
      293,  281,  282,  283,  284,  295,  296,  286,  287,  288,
      297,  298,  290,  299,  300,  303,  304,  265,  260,  252,
      249,  237,  226,  160,  144,  135,  100,   97,  293,   53,
       51,   49,   47,  295,  296,   44,   20,   19,  297,  298,
       15,  299,  300,  303,  304,  307,  307,  307,  307,  307,
      307,  307,  308,   14,  308,  308,  308,  308,  308,  309,
      309,   12,  309,  309,  309,  309,  310,  310,  311,    9,
      311,  314,    5,  314,  315,    4,  315,  315,  316,    3,
      316,  316,  316,  316,  316,  317,    0,  317,  306,  306,

      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  306
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[78] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Grammar.l"
#line 3 "Grammar.l"
#include "Grammar.tab.h"
#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include"tree.h"
extern int yyerror();
int do_begin();
int old_stat;

extern struct Global _Global;
 
//test
#line 739 "lex.yy.c"

#define INITIAL 0
#define NOTE_STAT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 20 "Grammar.l"

#line 924 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 307 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 599 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 21 "Grammar.l"
{do_begin();}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 22 "Grammar.l"
{Insert_str(yytext);return AS;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 23 "Grammar.l"
{Insert_str(yytext);return SELECT;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 25 "Grammar.l"
{ Insert_str(yytext);yylval.node = Create_new_node(SELECT_OPT,"ALL"); return ALL; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 26 "Grammar.l"
{Insert_str(yytext);yylval.node = Create_new_node(SELECT_OPT,"DISTINCT");return DISTINCT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 27 "Grammar.l"
{Insert_str(yytext);yylval.node = Create_new_node(SELECT_OPT,"DISTINCTROW");return DISTINCTROW;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 28 "Grammar.l"
{Insert_str(yytext);yylval.node = Create_new_node(SELECT_OPT,"TRAIGHT_JOIN");return STRAIGHT_JOIN;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 29 "Grammar.l"
{Insert_str(yytext);yylval.node = Create_new_node(SELECT_OPT,"SQL_SMALL_RESULT");return SQL_SMALL_RESULT;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 30 "Grammar.l"
{Insert_str(yytext);yylval.node = Create_new_node(SELECT_OPT,"SQL_BIG_RESULT");return SQL_BIG_RESULT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 31 "Grammar.l"
{Insert_str(yytext);yylval.node = Create_new_node(SELECT_OPT,"SQL_BUFFER_RESULT");return SQL_BUFFER_RESULT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 32 "Grammar.l"
{Insert_str(yytext);yylval.node = Create_new_node(SELECT_OPT,"SQL_NO_CACHE");return SQL_NO_CHACHE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 33 "Grammar.l"
{Insert_str(yytext);yylval.node = Create_new_node(SELECT_OPT,"SQL_CALC_FOUND_ROWS");return SQL_CALC_FOUND_ROWS;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 35 "Grammar.l"
{ Insert_str(yytext);return HIGH_PRIORITY; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 36 "Grammar.l"
{Insert_str(yytext);return FROM;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 37 "Grammar.l"
{Insert_str(yytext);return PARTITION;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 38 "Grammar.l"
{Insert_str(yytext);return WHERE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 39 "Grammar.l"
{Insert_str(yytext);return GROUP;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 40 "Grammar.l"
{Insert_str(yytext);return BY;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 41 "Grammar.l"
{Insert_str(yytext);return HAVING;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 42 "Grammar.l"
{Insert_str(yytext);return WINDOW;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 43 "Grammar.l"
{Insert_str(yytext);return ORDER;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 44 "Grammar.l"
{Insert_str(yytext);return LIMIT;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 45 "Grammar.l"
{Insert_str(yytext);return INTO;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 46 "Grammar.l"
{Insert_str(yytext);return INSERT;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 47 "Grammar.l"
{Insert_str(yytext);return UPDATE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 48 "Grammar.l"
{Insert_str(yytext);return SET;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 49 "Grammar.l"
{Insert_str(yytext);return CREATE;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 50 "Grammar.l"
{Insert_str(yytext);return DATABASE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 51 "Grammar.l"
{Insert_str(yytext);return JOIN;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 52 "Grammar.l"
{Insert_str(yytext);return INNER;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 53 "Grammar.l"
{Insert_str(yytext);return CROSS;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 54 "Grammar.l"
{Insert_str(yytext);return USING;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 55 "Grammar.l"
{Insert_str(yytext);return LEFT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 56 "Grammar.l"
{Insert_str(yytext);return RIGHT;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 57 "Grammar.l"
{Insert_str(yytext);return OUTER;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 58 "Grammar.l"
{Insert_str(yytext);return NATURAL;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 59 "Grammar.l"
{Insert_str(yytext);return ON;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 60 "Grammar.l"
{Insert_str(yytext);return AND;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 61 "Grammar.l"
{Insert_str(yytext);return OR;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 62 "Grammar.l"
{Insert_str(yytext);return IN;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 63 "Grammar.l"
{Insert_str(yytext);return NOT;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 64 "Grammar.l"
{Insert_str(yytext);return EXISTS;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 65 "Grammar.l"
{Insert_str(yytext);return UNION;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 66 "Grammar.l"
{Insert_str(yytext);return ASC;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 67 "Grammar.l"
{Insert_str(yytext);return DESC;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 68 "Grammar.l"
{Insert_str(yytext);return CASE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 69 "Grammar.l"
{Insert_str(yytext);return THEN;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 70 "Grammar.l"
{Insert_str(yytext);return WHEN;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 71 "Grammar.l"
{Insert_str(yytext);return END;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 72 "Grammar.l"
{Insert_str(yytext);return ELSE;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 73 "Grammar.l"
{Insert_str(yytext);return LIKE;}
	YY_BREAK
/*处理insert 语句的问题*/
case 52:
YY_RULE_SETUP
#line 77 "Grammar.l"
{Insert_str(yytext);return VALUES;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 78 "Grammar.l"
{Insert_str(yytext);yylval.strval = strdup(yytext);return NAME;} 
	YY_BREAK
/*处理等于和不等于*/
case 54:
YY_RULE_SETUP
#line 80 "Grammar.l"
{return EQ; } 
	YY_BREAK
/*处理系统变量 @@ 的情况*/
case 55:
YY_RULE_SETUP
#line 83 "Grammar.l"
{Insert_str(yytext);yylval.strval = strdup(yytext);return SYSTEM_CALL_VARIABLE;} 
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 84 "Grammar.l"
{Insert_str(yytext);yylval.strval = strdup(yytext);return USER_CALL_VARIABLE;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 86 "Grammar.l"
{Insert_str(yytext);yylval.strval = strdup(yytext);return NUM;}
	YY_BREAK
/*处理函数*/
case 58:
YY_RULE_SETUP
#line 88 "Grammar.l"
{Insert_str(yytext);yylval.strval = strdup(yytext);return NAME;}
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 89 "Grammar.l"
{Insert_str(yytext);yylval.strval = strdup(yytext);return NAME;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 90 "Grammar.l"
{Insert_str(yytext);yylval.strval = strdup(yytext);return NUM;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 91 "Grammar.l"
{Insert_str(yytext);  return yytext[0];}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 92 "Grammar.l"
{Insert_str(yytext);return yytext[0]; }
	YY_BREAK
/*处理注释*/
case 63:
YY_RULE_SETUP
#line 94 "Grammar.l"
{Insert_str(yytext);};
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 95 "Grammar.l"
{Insert_str(yytext);};
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 96 "Grammar.l"
{Insert_str(yytext); old_stat = YY_START; BEGIN NOTE_STAT;}
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 97 "Grammar.l"
{Insert_str(yytext);};
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 98 "Grammar.l"
{Insert_str(yytext);BEGIN old_stat;}
	YY_BREAK
/*处理当读到文件结束也没有发现注释结束的符号*/
case YY_STATE_EOF(NOTE_STAT):
#line 100 "Grammar.l"
{BEGIN old_stat; yyerror("你的注释没有结束，文件以结束，检查文件\n");}
	YY_BREAK
/*处理比较的符号 返回 EQ */
case 68:
YY_RULE_SETUP
#line 102 "Grammar.l"
{Insert_str(yytext);yylval.strval = strdup(yytext);return EQ;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 103 "Grammar.l"
{Insert_str(yytext);yylval.strval = strdup(yytext);return EQ;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 104 "Grammar.l"
{Insert_str(yytext);yylval.strval = strdup(yytext);return EQ;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 105 "Grammar.l"
{Insert_str(yytext);yylval.strval = strdup(yytext);return EQ;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 106 "Grammar.l"
{Insert_str(yytext);yylval.strval = strdup(yytext);return EQ;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 107 "Grammar.l"
{Insert_str(yytext);yylval.strval = strdup(yytext);return EQ;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 109 "Grammar.l"
{Insert_str(yytext);}  
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 110 "Grammar.l"
{Insert_str(yytext);}  
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 111 "Grammar.l"
{ yyerror(" Mystery character=%s! ",yytext);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 112 "Grammar.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1416 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 307 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 307 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 306);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 112 "Grammar.l"



int do_begin()
{
    yyin = fopen("liuyu","r");
    return 1;
}

